### ISSUE TITLE
Smart computer firing

### ISSUE THREAD

**Issue by zainkai** [OSU-CS361-W17/group2_project4#5]
Give the computer a "Hard mode" where it detects if it hit a ship, if it did it must fire on adjacent squares looking to kill the other ship tiles. Refer to Marks pseudo code for help.

**Comment by Makumasa** [comment]
Assigned myself to this task because Joseph and I are working together on this. I designed the psuedocode for the algorithm and did debugging/refactoring of Joseph's skeleton code.

**Comment by Makumasa** [comment]
Computer AI now mostly works. Don't have time to iron it out any further.
